from __future__ import annotations

import argparse
import ipaddress
import json
from pathlib import Path

from .stage_m import build_specs

WINDOWS_FAMILIES = {
    "M-HTTPS-BEACON", "M-HTTPS-FRONT", "M-HTTPS-LOWENT", "M-HTTPS-FRAG",
    "M-CLOUD-API", "M-RMM-SHAPE", "M-WSS-LONG", "M-TUNNEL",
    "M-DNS-BEACON", "M-DNS-BULK",
}
WINDOWS_HTTP_STACKS = ("dotnet_httpclient_schannel", "winhttp", "curl_schannel")


def _private_ip(value: str) -> bool:
    try:
        ip = ipaddress.ip_address(value)
        return ip.is_private and not ip.is_loopback
    except ValueError:
        return False


def load_inventory(path: Path) -> dict:
    inv = json.loads(path.read_text())
    clients = inv.get("clients") or []
    if not clients:
        raise ValueError("VM inventory has no clients")
    server_ip = str((inv.get("server") or {}).get("ipv4", ""))
    if not _private_ip(server_ip):
        raise ValueError("server.ipv4 must be a private lab address")
    for c in clients:
        if not _private_ip(str(c.get("ipv4", ""))):
            raise ValueError(f"client {c.get('id')} must use a private lab address")
        if c.get("os") not in {"linux", "windows"}:
            raise ValueError(f"unsupported client os: {c.get('os')}")
    return inv


def choose_client(spec, inv: dict) -> tuple[dict, str, str]:
    linux = [c for c in inv["clients"] if c["os"] == "linux"]
    windows = [c for c in inv["clients"] if c["os"] == "windows"]

    # Roughly 25% of compatible P0 traffic is generated by Windows-native
    # stacks. One Windows stack is marked H_client rather than train so the
    # release can test implementation generalization.
    if windows and spec.family in WINDOWS_FAMILIES and spec.index % 4 == 0:
        c = windows[(spec.index // 4) % len(windows)]
        if spec.family in {"M-WSS-LONG", "M-TUNNEL"}:
            stack = "dotnet_clientwebsocket"
        elif spec.family.startswith("M-DNS"):
            stack = "windows_dns"
        else:
            stack = WINDOWS_HTTP_STACKS[(spec.index // 4) % len(WINDOWS_HTTP_STACKS)]
        split_role = "H_client" if stack == "curl_schannel" else "train"
        return c, stack, split_role

    if not linux:
        raise ValueError(f"no Linux client available for {spec.family}")
    c = linux[spec.index % len(linux)]
    return c, spec.client_impl, "train"


def make_plan(inv: dict, mode: str, shard: int, shards: int) -> list[dict]:
    rows = []
    for spec in build_specs(mode):
        if spec.index % shards != shard:
            continue
        client, stack, split_role = choose_client(spec, inv)
        rows.append({
            "campaign_id": f"vm-m-{spec.index:05d}-{spec.family_index:04d}",
            "spec_index": spec.index,
            "family": spec.family,
            "family_index": spec.family_index,
            "implementation_id": f"vm-{client['id']}-{stack}-{spec.implementation_id}",
            "base_implementation_id": spec.implementation_id,
            "client_id": client["id"],
            "client_os": client["os"],
            "client_ssh": client["ssh"],
            "source_ip": client["ipv4"],
            "client_impl": stack,
            "server_impl": spec.server_impl,
            "front_host": spec.front_host,
            "network_topology": spec.network_topology,
            "interval_seconds": spec.interval_seconds,
            "interval_bucket_seconds": spec.interval_bucket_seconds,
            "jitter_fraction": spec.jitter_fraction,
            "event_count": spec.event_count,
            "event_count_bucket": spec.event_count_bucket,
            "volume_mode": spec.volume_mode,
            "asymmetry": spec.asymmetry,
            "payload_mode": spec.payload_mode,
            "holdout_fold": spec.holdout_fold,
            "split_role": split_role,
            "training_eligible": split_role == "train",
            "capture_environment": "vm_wire",
            "positive_only": True,
            "label_binary": 1,
        })
    return rows


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--inventory", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--mode", choices=["smoke", "full"], default="smoke")
    ap.add_argument("--shard", type=int, default=0)
    ap.add_argument("--shards", type=int, default=1)
    a = ap.parse_args()
    if a.shards < 1 or not 0 <= a.shard < a.shards:
        raise SystemExit("invalid shard/shards")
    inv = load_inventory(Path(a.inventory))
    rows = make_plan(inv, a.mode, a.shard, a.shards)
    out = Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(json.dumps(r, separators=(",", ":")) for r in rows) + ("\n" if rows else ""))
    print(json.dumps({
        "campaigns": len(rows),
        "mode": a.mode,
        "shard": a.shard,
        "shards": a.shards,
        "windows": sum(r["client_os"] == "windows" for r in rows),
        "linux": sum(r["client_os"] == "linux" for r in rows),
        "train": sum(r["training_eligible"] for r in rows),
        "h_client": sum(r["split_role"] == "H_client" for r in rows),
        "positive_only": True,
    }, sort_keys=True))


if __name__ == "__main__":
    main()
