#!/usr/bin/env python3
"""Generate the Lua side of the fast-v1 contract from its one Python source.

Two problems this removes.

The exporter wrote no `contract_hash`, so a consumer loading models in strict
mode rejected every real Suricata record as `rejected_schema`. The hash cannot
be computed in Lua — it is a sha256 over a canonical JSON payload — so it has to
be carried there.

And the horizon constants lived twice, once in `online_schema.py` and once as
literals at the top of `first20.lua`. Changing MIN_PACKETS from 4 to 3 meant
editing both by hand; whoever forgot the second edit would have had a sensor
computing a different vector than the model was trained on, with a hash claiming
they matched. Generating the Lua constants makes that particular drift
impossible rather than merely tested for.

Run after any change to the contract:
    python3 lab_pipeline/emit_lua_contract.py
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

_PKG_ROOT = Path(__file__).resolve().parent.parent
if str(_PKG_ROOT) not in sys.path:
    sys.path.insert(0, str(_PKG_ROOT))

from lab_pipeline.online_schema import (  # noqa: E402
    FLOW_TIMEOUTS,
    OUT_OF_SCOPE_PORTS,
    MAX_PACKETS,
    MAX_SECONDS,
    MIN_PACKETS,
    REDUCER_REVISION,
    SCHEMA_VERSION,
    contract_hash,
)

DEFAULT_OUT = _PKG_ROOT / "suricata" / "lua" / "contract.lua"


def render() -> str:
    ports = ", ".join(f"[{p}] = true" for p in OUT_OF_SCOPE_PORTS)
    return f'''-- GENERATED by lab_pipeline/emit_lua_contract.py -- DO NOT EDIT.
--
-- The fast-v1 contract as first20.lua needs it. Regenerate after any change to
-- lab_pipeline/online_schema.py; test_lua_parity fails if this file drifts.
return {{
    SCHEMA_VERSION  = "{SCHEMA_VERSION}",
    CONTRACT_HASH   = "{contract_hash()}",
    REDUCER_REVISION = {REDUCER_REVISION},
    MAX_PACKETS     = {MAX_PACKETS},
    MAX_SECONDS     = {float(MAX_SECONDS)},
    MIN_PACKETS     = {MIN_PACKETS},
    OUT_OF_SCOPE_PORTS = {{ {ports} }},
    TIMEOUTS = {{
        tcp_new = {float(FLOW_TIMEOUTS["tcp"]["new"])},
        tcp_est = {float(FLOW_TIMEOUTS["tcp"]["established"])},
        udp_new = {float(FLOW_TIMEOUTS["udp"]["new"])},
        udp_est = {float(FLOW_TIMEOUTS["udp"]["established"])},
    }},
}}
'''


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the file on disk is stale, write nothing")
    args = ap.parse_args()

    out = Path(args.out)
    want = render()
    if args.check:
        have = out.read_text() if out.exists() else ""
        if have != want:
            print(f"stale: {out} does not match online_schema.py")
            return 1
        print(f"current: {out}")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(want, encoding="utf-8")
    print(f"wrote {out} (contract {contract_hash()[:16]})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
