#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from adminlab.config import load_yaml, validate_feature_contract  # noqa: E402
from adminlab.features import select_model_columns  # noqa: E402
from adminlab.splits import assign_grouped_splits, audit_leakage  # noqa: E402


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def scoped(shard: str, value: object) -> str:
    text = str(value or "")
    return "" if not text else f"{shard}::{text}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--feature-contract", type=Path, default=ROOT / "configs/feature_contract.yaml")
    ap.add_argument("--split-seed", type=int, default=20260814)
    args = ap.parse_args()

    contract = load_yaml(args.feature_contract)
    validate_feature_contract(contract)
    feature_files = sorted(args.root.glob("**/gold/*/production_flow_features.parquet"))
    if not feature_files:
        raise SystemExit("no production flow Gold shards found")

    sessions_parts: list[pd.DataFrame] = []
    features_parts: list[pd.DataFrame] = []
    labels_parts: list[pd.DataFrame] = []
    shard_rows: list[dict] = []
    seen_shards: set[str] = set()

    for fp in feature_files:
        shard = fp.parent.name
        if shard in seen_shards:
            raise SystemExit(f"duplicate Gold shard name in merge input: {shard}")
        seen_shards.add(shard)
        release = fp.parents[2]
        label_path = fp.parent / "production_flow_labels.parquet"
        sessions_path = release / "bronze" / shard / "manifests/sessions.parquet"
        if not label_path.is_file() or not sessions_path.is_file():
            raise SystemExit(f"incomplete production shard {shard}")

        features = pd.read_parquet(fp).copy()
        labels = pd.read_parquet(label_path).copy()
        sessions = pd.read_parquet(sessions_path).copy()
        if len(features) != len(labels):
            raise SystemExit(f"feature/label row mismatch {shard}")
        if features["flow_uid"].duplicated().any():
            raise SystemExit(f"duplicate Zeek flow UID inside shard {shard}")

        # IDs generated by independent VM shards are local namespaces. Scope
        # behavioral/campaign/counterfactual IDs before global DSU grouping.
        session_map = {value: scoped(shard, value) for value in sessions["session_id"].astype(str).unique()}
        sessions["session_id"] = sessions["session_id"].astype(str).map(session_map)
        labels["session_id"] = labels["session_id"].astype(str).map(session_map)
        features["session_id"] = features["session_id"].astype(str).map(session_map)
        for column in ("campaign_id", "pair_id"):
            if column in sessions.columns:
                sessions[column] = sessions[column].map(lambda value: scoped(shard, value))
            if column in labels.columns:
                labels[column] = labels[column].map(lambda value: scoped(shard, value))

        features["global_flow_id"] = shard + "::" + features["flow_uid"].astype(str)
        labels["global_flow_id"] = shard + "::" + labels["flow_uid"].astype(str)
        labels["dataset_shard"] = shard
        sessions["dataset_shard"] = shard
        features_parts.append(features)
        labels_parts.append(labels)
        sessions_parts.append(sessions)
        shard_rows.append({"shard": shard, "sessions": int(len(sessions)), "flows": int(len(features))})

    sessions = pd.concat(sessions_parts, ignore_index=True)
    features = pd.concat(features_parts, ignore_index=True)
    labels = pd.concat(labels_parts, ignore_index=True)
    if sessions["session_id"].duplicated().any():
        raise SystemExit("duplicate scoped behavioral session IDs globally")
    if features["global_flow_id"].duplicated().any() or labels["global_flow_id"].duplicated().any():
        raise SystemExit("duplicate scoped global flow IDs")

    joined = features.merge(
        labels,
        on=["global_flow_id", "flow_uid", "session_id"],
        how="inner",
        validate="one_to_one",
        suffixes=("", "_label"),
    )
    coverage = len(joined) / len(features) if len(features) else 0.0
    if coverage < 0.999:
        raise SystemExit(f"feature-label flow coverage below .999: {coverage}")

    splits, split_report = assign_grouped_splits(sessions, seed=args.split_seed)
    force_sessions = set(
        sessions.loc[sessions["dataset_shard"].astype(str).str.startswith("H-"), "session_id"].astype(str)
    )
    if "semantic_fidelity" in labels.columns:
        force_sessions |= set(
            labels.loc[labels["semantic_fidelity"].astype(str).eq("partial_winrm"), "session_id"].astype(str)
        )
    group_map = splits.set_index("session_id")["group_id"]
    forced_groups = set(group_map.reindex(list(force_sessions)).dropna().astype(str))
    if not forced_groups:
        raise SystemExit("Stage H / partial-WinRM challenge policy matched zero groups")
    splits.loc[splits["group_id"].astype(str).isin(forced_groups), "split"] = "challenge"
    split_map = splits.set_index("session_id")["split"]
    joined["split"] = joined["session_id"].map(split_map)
    if joined["split"].isna().any():
        raise SystemExit("global flow split missing")

    selected = select_model_columns(joined, contract)
    matrix = selected.copy()
    matrix["label_binary"] = joined["label_binary"].astype(int).to_numpy()
    matrix["split"] = joined["split"].astype(str).to_numpy()
    leakage = audit_leakage(sessions, splits, list(matrix.columns), contract, split_report)
    if not leakage["ok"]:
        raise SystemExit(json.dumps(leakage, sort_keys=True))

    out = args.out
    gold = out / "gold"
    quality = out / "quality"
    gold.mkdir(parents=True, exist_ok=True)
    quality.mkdir(parents=True, exist_ok=True)
    joined.to_parquet(gold / "production_flow_features_and_labels.parquet", index=False)
    splits.to_parquet(gold / "behavioral_session_splits.parquet", index=False)
    matrix.to_parquet(gold / "production_model_matrix.parquet", index=False)
    report = {
        "shards": shard_rows,
        "shard_count": len(shard_rows),
        "behavioral_sessions": int(len(sessions)),
        "production_flows": int(len(matrix)),
        "flow_join_coverage": float(coverage),
        "feature_count": int(len(selected.columns)),
        "forced_challenge_sessions": int(len(force_sessions)),
        "forced_challenge_groups": int(len(forced_groups)),
        "split_counts": {str(k): int(v) for k, v in matrix["split"].value_counts().to_dict().items()},
        "leakage_ok": True,
        "production_unit": "parser_flow",
        "id_namespace_policy": "shard::local_id for session/campaign/pair/flow; host identities remain global holdout keys",
    }
    write_json(quality / "production_merge.json", report)
    write_json(quality / "production_leakage.json", leakage)
    write_json(quality / "global_split_report_pre_challenge_override.json", split_report)
    print(json.dumps(report, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
